baseURL = "https://tvjussieu.netlify.app"
title = "TVJUSSIEU"
author = "yoyolejojo"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
sectionPagesMenu = 'main'


# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""



[params]


  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/Logo_TVJ.png"
    

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "TV Jussieu"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true


  [params.homepage_meta_tags]
    meta_description = "Le site de TV Jussieu pour avoir toutes les informations sur nos activités etc."
    meta_og_title = "tvjussieu"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Le site de TV Jussieu pour avoir toutes les informations sur nos activités etc."


[menu]

  [[menu.main]]
    identifier = "blog"
    name = "PROJET"
    url = "/blog/"
    weight = 1 

  [[menu.main]]
    identifier = "about"
    name = "NOUS"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3


  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

